### ISSUE TITLE
UserStory2

### ISSUE THREAD

**Issue by CeMaGo** [CeMaGo/Spiced-Final-Project-Template#3]
## Value proposition

As an <User> I want to have a easy overview
I want a to be able to easily navigate through my account
So that I can access my desired content hussel-free.

## Description

- Scribble / Easy Access Navigation Bar / profile-Button
- Having a NavBar with Section for Home/ Player / Lib
- Upper right corner shall get a Profile Button

## Acceptance criteria

- [ ] What happens when an entry is empty? display Error, callback to previous page, or default homepage
- [ ] How should something behave? when a Button in the Navigation is clicked, it should change to the requested page.

## Tasks

- [ ] create a NavBar Component
- [ ] It should get 3 Buttons (for Now) Home, Player, Library.
- [ ] Make a Profile Button for the Upper right corner, should display on all pages except the profile page
- [ ] pass NavBar to Homepage
