### ISSUE TITLE
#UserStory 3

### ISSUE THREAD

**Issue by CeMaGo** [CeMaGo/Spiced-Final-Project-Template#4]
focus on displaying content, daily feature, list of available item
## Title
user Story 3.1
## Value proposition

As an <User>
I want a good overview of the content.
So that <benefit> I can find what i am looking for as well as browse new content. And maybe even find what, i didn't know, i was looking for.

## Description

- page with Daily feature displayed
- a list of the  content , clickable, fav button
-NavBar displayed on the bottom
## Acceptance criteria

- [ ] A daily Feature is displayed at the top
- [ ] underneath the daily is a List of (Audio)Files with short description displayed.
- [ ] ListItems get a Liked button which toggles filled/outlined
- [ ] the Bottom displays the NavBar.

## Tasks

- [ ] built a DailyFeatureComponent, it receives a random Audiofile daily
- [ ] display a list of the content, scrollable 
- [ ] if title is not available, display a polite error message
