### ISSUE TITLE
#UserStory1

### ISSUE THREAD

**Issue by CeMaGo** [CeMaGo/Spiced-Final-Project-Template#5]
## Value proposition

As an User I want to be able to LogIn/Creat an Account
So I can have access to my account
This should be as convinent as possible

## Description

- Display a form with input for Username, Password, or/and Third-part sign in. and a Submit/login Button

## Acceptance criteria

- [ ] What happens when an entry is empty?
- [ ] How should something behave?
- [ ] What is the text of an alert?

## Tasks

- [ ] Create a LogIn Component
- [ ] Import the Login Component to the main Page
- [ ] It should check if the User already exists or give the option to create an account
- [ ] After successful signIn, User Should be redirected to the main page
