### ISSUE TITLE
#UserStory4

### ISSUE THREAD

**Issue by CeMaGo** [CeMaGo/Spiced-Final-Project-Template#6]
## Title
user Story 4 should focus on Seachbar

As an <User>
I want a good overview of the content and to be able to interact with it
So that <benefit> I can find what i am looking for as well as browse new content. And maybe even find what, i didn't know, i was looking for. -->

## Description

-  to the left of the Content-list-item a pre-pay button
-lower half gets a search bar
## Acceptance criteria

- [ ] there is a play button to the right, which should give a pre-listen when held/hovered down/over.
- [ ] ListItems get a Liked button which toggles filled/outlined
- [ ] the Search bar input should receive text, and give proper feedback

## Tasks

- [ ] pre-playButton, should start a short 15sec preview-play when held-down
- [ ] built a Search bar component, it should filter the content, and display the requested title.
- [ ] if title is not available, display a polite error message -->
