### ISSUE TITLE
#UserStory 5

### ISSUE THREAD

**Issue by CeMaGo** [CeMaGo/Spiced-Final-Project-Template#7]
## Value proposition

As an User 
I want a have a personalized experience and safe my favorites
So that <> I can have easy access to the good stuff

## Description

![](./userStory03.excalidraw)
- Scribble / design or text
- Profile Picture/ avatar
- Home Button "/"

## Acceptance criteria

- [ ] When clicking the "HomeButton" the user is redirected to the main page.
- [ ] In the upper Left Corner is a Profile-Picture or default Avatar displayed
- [ ] the Lower half of the Profile page displays a list of Favorite Audio-files.
 - [ ] On the right next to the listItem should be the like button, on click files can be taken out of the favorite list aka Toggle.
 - [ ] when clicked on the List item of Favorite-Tracks, one should be directed to the player with clicked audio file ready to play. (future function or sub Story)
## Tasks

- [ ] make a profile page
- [ ] built a ProfilePictureComponent. it should receive a picture prop from the Oauth-fetched data to display, or have a default avatar displayed.
- [ ] make a ListComponent it receives Content via Liked-Toggle and displays the audio file as list items.
- make a HomeButtonComponent and render it in the top righty corner
